# Generated by Django 5.1 on 2024-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_transaction_status_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
