# Generated by Django 5.1 on 2024-09-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_transaction_destination_account_number_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
    ]
